name: Deploy Documentation

on:
  push:
    branches: [master]
    tags:
      - 'v[0-9]+.[0-9]+.0'  # Only deploy docs for feature releases (x.y.0)
  workflow_dispatch:

permissions:
  contents: write  # Need write access to push to gh-pages branch
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for mike versioning

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync
        uv add mkdocs-material mike

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Determine version strategy
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          # Tagged release - extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_release=true" >> $GITHUB_OUTPUT
        else
          # Push to master - deploy as 'dev'
          echo "version=dev" >> $GITHUB_OUTPUT
          echo "is_release=false" >> $GITHUB_OUTPUT
        fi

    - name: Deploy versioned docs (feature release)
      if: steps.version.outputs.is_release == 'true'
      run: |
        uv run mike deploy ${{ steps.version.outputs.version }} latest --update-aliases --push
        uv run mike set-default latest --push

    - name: Deploy development docs
      if: steps.version.outputs.is_release == 'false'
      run: |
        uv run mike deploy dev --push

    - name: Build and deploy site
      run: |
        # Build the current version
        uv run mkdocs build
        # Note: mike handles the gh-pages branch deployment